# K8s for calculator app / image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-Deployment
  labels: 
    app: myapp
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gowrinth225/myapp-3.5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
# Service Object To Access Application
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: myapp
        
  
