# K8s for calculator app / image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-new
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gowrinth225/myapp-3.5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
  # Service Object To Access Application
apiVersion: v1
kind: Service
metadata:
  name: myapp-new
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: myapp
